//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poseidon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.User = new HashSet<User>();
            this.Logger = new HashSet<Logger>();
        }
    
        public int company_id { get; set; }
        public string company_name { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public string company_description { get; set; }
    
        public virtual ICollection<User> User { get; set; }
        public virtual ICollection<Logger> Logger { get; set; }
    }
}
