//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poseidon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Logger = new HashSet<Logger>();
        }
    
        public int company_id { get; set; }
        public string company_name { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public string company_description { get; set; }
    
        public virtual ICollection<Logger> Logger { get; set; }
    }
}
