//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poseidon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public int customer_id { get; set; }
        public string customer_name { get; set; }
        public Nullable<int> customer_company_id { get; set; }
        public string customer_email { get; set; }
        public Nullable<bool> cc { get; set; }
    }
}
