<?xml version="1.0" encoding="utf-8"?><Database Name="poseidon_db" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=158.85.25.234;Initial Catalog=poseidon_db;User ID=jonathan-desarrollo;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="poseidon_dbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Company" Member="Company">
    <Type Name="Company">
      <Column Name="company_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="company_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="creation_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="company_description" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Company_Logger" Member="Logger" ThisKey="company_id" OtherKey="company_id" Type="Logger" />
      <Association Name="Company_User" Member="User" ThisKey="company_id" OtherKey="company_id" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.Logger" Member="Logger">
    <Type Name="Logger">
      <Column Name="logger_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="logger_sites_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="logger_sms" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="logger_type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="logger_serial_number" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="instalation_type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="chip_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="latitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="longitute" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="elevation" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="antenna_position" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="final_csq" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="gprs_test_status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="creation_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="creation_user" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="instalation_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="instalation_user" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="approval_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="approval_user" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="company_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="zone_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="url_image" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="location_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="location_id" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Company_Logger" Member="Company" ThisKey="company_id" OtherKey="company_id" Type="Company" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="User">
    <Type Name="User">
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="user_creation" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="user_type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="company_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_pass" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="user_login" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Company_User" Member="Company" ThisKey="company_id" OtherKey="company_id" Type="Company" IsForeignKey="true" />
      <Association Name="UserType_User" Member="UserType" ThisKey="user_type_id" OtherKey="user_type_id" Type="UserType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserType" Member="UserType">
    <Type Name="UserType">
      <Column Name="user_type_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="user_type_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="UserType_User" Member="User" ThisKey="user_type_id" OtherKey="user_type_id" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.Zone" Member="Zone">
    <Type Name="Zone">
      <Column Name="zone_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="zone_name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="zone_code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>