//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poseidon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logger
    {
        public int logger_id { get; set; }
        public string logger_sites_name { get; set; }
        public Nullable<int> logger_sms { get; set; }
        public Nullable<int> logger_type { get; set; }
        public string logger_serial_number { get; set; }
        public Nullable<int> instalation_type { get; set; }
        public Nullable<int> chip_id { get; set; }
        public string latitude { get; set; }
        public string longitute { get; set; }
        public Nullable<double> elevation { get; set; }
        public string antenna_position { get; set; }
        public Nullable<int> final_csq { get; set; }
        public bool gprs_test_status { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public Nullable<int> creation_user { get; set; }
        public Nullable<System.DateTime> instalation_date { get; set; }
        public Nullable<int> instalation_user { get; set; }
        public Nullable<System.DateTime> approval_date { get; set; }
        public Nullable<int> approval_user { get; set; }
        public int company_id { get; set; }
        public string url_image { get; set; }
        public Nullable<int> status { get; set; }
        public string location_name { get; set; }
        public string location_id { get; set; }
        public bool necessary_key { get; set; }
        public string contact_detail { get; set; }
        public string zone_name { get; set; }
        public string zone_code { get; set; }
        public string sites_name { get; set; }
        public bool key_ball { get; set; }
        public Nullable<int> zone_id { get; set; }
        public Nullable<int> user_instalation { get; set; }
        public Nullable<System.DateTime> user_instalation_start_date { get; set; }
        public Nullable<System.DateTime> user_instalation_end_date { get; set; }
        public bool necesary_site_enter { get; set; }
        public bool logger_outdoor { get; set; }
        public string condition_type_instalation { get; set; }
        public Nullable<int> antenna_type { get; set; }
        public bool Csq_outdoor { get; set; }
        public bool can_lamppost_with_antenna { get; set; }
        public string manometer_aar_value { get; set; }
        public string logger_aar_value { get; set; }
        public string manometer_aab_value { get; set; }
        public string logger_aab_value { get; set; }
        public string flowmetter_status { get; set; }
        public bool with_pulser { get; set; }
        public bool pulser_changed { get; set; }
        public string liters_per_pulser { get; set; }
        public string logger_position { get; set; }
        public bool flooded_chamber { get; set; }
        public string chamber_condition { get; set; }
        public string chamber_cap { get; set; }
        public bool necessary_drain { get; set; }
        public bool necessary_manipulate_traffic { get; set; }
        public bool necessary_tool_open_chamber { get; set; }
        public bool two_thechnical_open_chamber { get; set; }
        public Nullable<int> channel_1 { get; set; }
        public Nullable<int> channel_2 { get; set; }
        public Nullable<int> channel_3 { get; set; }
        public Nullable<int> channel_4 { get; set; }
        public bool battery_installed { get; set; }
        public string battery_serial_number { get; set; }
        public string notes { get; set; }
        public string site_conditions_installation { get; set; }
        public Nullable<int> id_conditions_installation { get; set; }
        public Nullable<int> chamber_type_id { get; set; }
        public Nullable<int> chamber_type_tap_id { get; set; }
        public string battery_type { get; set; }
        public Nullable<int> state_flowmeter_id { get; set; }
        public Nullable<int> type_flowmeter_id { get; set; }
        public string picture_image { get; set; }
        public string picture_url { get; set; }
        public string instalation_type_logger { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
