//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poseidon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logger
    {
        public int logger_id { get; set; }
        public string logger_sites_name { get; set; }
        public Nullable<int> logger_sms { get; set; }
        public Nullable<int> logger_type { get; set; }
        public string logger_serial_number { get; set; }
        public Nullable<int> instalation_type { get; set; }
        public Nullable<int> chip_id { get; set; }
        public string latitude { get; set; }
        public string longitute { get; set; }
        public Nullable<double> elevation { get; set; }
        public string antenna_position { get; set; }
        public Nullable<int> final_csq { get; set; }
        public Nullable<bool> gprs_test_status { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public Nullable<int> creation_user { get; set; }
        public Nullable<System.DateTime> instalation_date { get; set; }
        public Nullable<int> instalation_user { get; set; }
        public Nullable<System.DateTime> approval_date { get; set; }
        public Nullable<int> approval_user { get; set; }
        public int company_id { get; set; }
        public string url_image { get; set; }
        public Nullable<int> status { get; set; }
        public string location_name { get; set; }
        public string location_id { get; set; }
        public Nullable<bool> necessary_key { get; set; }
        public string contact_detail { get; set; }
        public string zone_name { get; set; }
        public string zone_code { get; set; }
        public string sites_name { get; set; }
        public Nullable<bool> key_ball { get; set; }
        public Nullable<int> zone_id { get; set; }
        public Nullable<int> user_instalation { get; set; }
        public Nullable<System.DateTime> user_instalation_start_date { get; set; }
        public Nullable<System.DateTime> user_instalation_end_date { get; set; }
    
        public virtual Company Company { get; set; }

         public int PictureId { get; set; }
        public string PictureName { get; set; }
        public string PictureUrl { get; set; }
        public bool Status { get; set; }
    



    }
}
