//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poseidon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public Nullable<System.DateTime> user_creation { get; set; }
        public int user_type_id { get; set; }
        public int company_id { get; set; }
        public string user_pass { get; set; }
        public string user_login { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
